### ISSUE TITLE
Symfony 5 Sonata Admin

### ISSUE THREAD

**Issue by gekomod** [nucleos/NucleosUserAdminBundle#274]
#### Packages

```
$ composer show --latest
# Put the result here.
```

#### PHP version

```
$ php -v
# Put the result here.
```

## Actual results

  Problem 1
    - Root composer.json requires nucleos/user-admin-bundle 1.5.x-dev -> satisfiable by nucleos/user-admin-bundle[1.5.x-dev].
    - nucleos/user-admin-bundle 1.5.x-dev requires sonata-project/admin-bundle ^3.90 -> found sonata-project/admin-bundle[3.90.0, ..., 3.x-dev] but it conflicts with your root composer.json require (dev-master).

**Comment by core23** [comment]
Relies on the next SonataAdminBundle major version: https://github.com/sonata-project/SonataAdminBundle/pull/6476

**Comment by core23** [comment]
Done with #372
