### ISSUE TITLE
Sonata Admin and user list

### ISSUE THREAD

**Issue by gekomod** [nucleos/NucleosUserAdminBundle#276]
'PHP message: [critical] Uncaught PHP Exception LogicException: ""Nucleos\\UserAdminBundle\\Controller\\UserCRUDController" has no container set, did you forget to define it as a service subscriber?"

Symfony 5
Sonata-admin - Dev-master

**Comment by core23** [comment]
Can you please provide a *little more* information.

It looks like you try to use an unsupported symfony version. Maybe it relates to https://github.com/nucleos/NucleosUserAdminBundle/issues/274?
